// svetle-ext/src/Counter.svelte
<script>
  let count = 0

  const handlerIncrease = () => count++
  const handlerDecrease = () => count--
</script>

<div>
  <h2>Counter</h2>
  <p>
    Counter:
    <b class:green={count > 0} class:red={count < 0}> {count}</b>
  </p>
  <button on:click={handlerIncrease}>-</button>
  <button on:click={handlerDecrease}>+</button>
</div>

<style>
  div {
    width: 120px;
  }
  .red {
    color: red;
  }
  .green {
    color: green;
  }
  button {
    width: 50px;
  }
</style>

// react-ext/src/Counter.js
import { useState } from "react"

const Counter = () => {
  const [count, setCounter] = useState(0)

  const increment = () => {
    setCounter(count - 1)
  }
  
  const decrement = () => {
    setCounter(count + 1)
  }
  
  const getColor = () => {
    if (count === 0) return ''
    if (count > 0 ) return 'green'
    if (count < 0 ) return 'red'
  }

  return (
    <div>
      <h2>Counter</h2>
      <p>Counter: 
        <b className={getColor()}>
          {count}
        </b>
      </p>
      <button onClick={increment}>-</button>
      <button onClick={decrement}>+</button>
    </div>
  )
}

export { Counter }
